name: My test workflow

on:
  push:
    branches:
      - main
    paths:
      - 'gradle.properties'

env:
  COMMIT_MESSAGE: |
    Update Baseline Profile

    Created by GitHub Action [${{ github.workflow }} #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

    ACLOVERRIDE CODEOWNEROVERRIDE CUSTOMVALIDATIONSOVERRIDE

jobs:
  update-badge:
    runs-on: ubuntu-latest

    permissions:
      # contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README Badge
        run: |
          version=$(grep '^version' gradle.properties | cut -d= -f2 | tr -d '[:space:]')
          echo "1: $version"
          version=$(echo "$version" | sed 's/-/%E2%80%90/g')
          echo "2: $version"
